### ISSUE TITLE
[REQUEST] Automatically kick a player when joined with a hacked client like ToolBox

### ISSUE THREAD

**Issue by WEATHERCRAFTYT1** [Bavfalcon9/Mavoric#78]
I was thinking when a player joins a game with a client. The game will automatically kick them and say a message. Can you do that

**Comment by Bavfalcon9** [comment]
With some clients this may be possible, I'll have to do some research. However currently I'm going to say this isn't possible due to limitations with client and server data. It's not possible for us to check if the client has a modified version of the game (it never will be internally). So unless the developers of these hacks left something for us to check when logging in, we can't do anything about it.

**Comment by WEATHERCRAFTYT1** [comment]
Yes because I wanted to prevent players with a lot of hacking experience from entering the console and not changing stuff just in game. Oh well that’s fine

**Comment by Bavfalcon9** [comment]
If players are breaching your console then that's a different issue, that mavoric will more than likely not be able to detect (at least at its current state).

**Comment by WEATHERCRAFTYT1** [comment]
Ok :(

**Comment by WEATHERCRAFTYT1** [comment]
Wait

**Comment by WEATHERCRAFTYT1** [comment]
I also want to request a anti force op. It prevents players from auto force op

**Comment by radondev** [comment]
I haven't seen a force-op in years, but it should be fairly easy to implement

**Comment by WEATHERCRAFTYT1** [comment]
ok
